### ISSUE TITLE
Removing all trailing whitespace in file takes multiple command invocations

### ISSUE THREAD

**Issue by kkm000** [madskristensen/TrailingWhitespace#15] opened 2015-01-07 03:51 UTC
Take the following file (in case GitHub's postring code "helps" me, each line is three '/' followed by 10 spaces)
```
\\\          
\\\          
\\\          
```
Place caret at line 1 char 1 and hit C+k C+\\. Whitespace trimmed at the end of lines 1 and 2, but not line 3. Sometimes it takes 3-5 command invocations to clean a file heavily infested with trailing whitespace!

I think the problem is that the editing code is not using text snapshots properly. Is it possible that every edit changes the CurrentSnapshot of the edit buffer, but the foreach in RemoveTrailingWhitespace() holds on to an old iterator? I do not understand what really happens. But the check of line/buffer length at line 90 suggests something fishy is going on. I can't imagine there should be any lines sticking far out of the edit buffer!

Why are not you using ITextEdit's? Here's a piece of code that did the trick in the extension that I abandoned after discoversing yours, but it did the trick:

```c#
    ITextBuffer buffer = _view.TextBuffer;
    if (!buffer.CheckEditAccess())
        return VSConstants.S_OK;

    ITextEdit edit = buffer.CreateEdit();
    ITextSnapshot snap = edit.Snapshot;

    foreach (ITextSnapshotLine line in snap.Lines) {
        string s = line.GetText();
        int ixe = s.Length;
        while (--ixe >= 0 && Char.IsWhiteSpace(s[ixe]));
        if (ixe < s.Length - 1) {
            int jb = line.Start.Position;
            edit.Delete(jb + ixe + 1, s.Length - ixe - 1);
        }
    }

    edit.Apply();
```

Of course, you would take advantage of the classifier instead. I have a hitch that projection buffers can also be edited this way. In this case, you wouldn't even need the undo braces from the DTE.

**Comment by akatakritos** [comment] 2015-01-09 01:47
I noticed this today as well.

**Comment by madskristensen** [comment] 2015-01-09 16:18
This might have been fixed in the latest version. Can you update to the latest version and see if the issue is still there?

**Comment by kkm000** [comment] 2015-01-09 18:30
I have v1.9, and there are no updates available. I know you made some changes to the trimming code in this version (I think previously it worked only on visible lines--or that was my impression), but the problem I am describing is there.

**Comment by madskristensen** [comment] 2015-01-09 19:25
Ok, thanks for double checking. I'll take a look

**Comment by madskristensen** [comment] 2015-01-16 06:07
@kkm000 Thanks, that works beautifully

**Closed** 2015-01-16 06:08 UTC
Labels: bug
